import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';

class PdfReporter {
  constructor(options = {}) {
    this.outputFile = options.outputFile || `test-reports/test-report-${new Date().toISOString().slice(0, 10)}.pdf`;
    this.results = [];
    this.startTime = null;
    this.endTime = null;
    this.suiteName = 'CIFF E2E Test Automation Suite v3.0.0';
  }

  onBegin(config, suite) {
    this.startTime = new Date();
    this.totalTests = suite.allTests().length;
    console.log(`\n📋 PDF Reporter: Tracking ${this.totalTests} tests...\n`);
  }

  onTestEnd(test, result) {
    const screenshots = [];
    for (const attachment of result.attachments) {
      if (attachment.contentType && attachment.contentType.startsWith('image/')) {
        screenshots.push({
          name: attachment.name,
          path: attachment.path,
          contentType: attachment.contentType,
        });
      }
    }

    this.results.push({
      title: test.title,
      suite: test.parent ? test.parent.title : 'Unknown',
      project: test.parent?.project()?.name || 'unknown',
      status: result.status,
      duration: result.duration,
      error: result.error ? result.error.message : null,
      errorStack: result.error ? result.error.stack : null,
      retry: result.retry,
      screenshots,
    });
  }

  async onEnd(result) {
    this.endTime = new Date();
    const totalDuration = this.endTime - this.startTime;

    const dir = path.dirname(this.outputFile);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    const passed = this.results.filter(r => r.status === 'passed').length;
    const failed = this.results.filter(r => r.status === 'failed').length;
    const skipped = this.results.filter(r => r.status === 'skipped').length;
    const timedOut = this.results.filter(r => r.status === 'timedOut').length;

    const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true });
    const stream = fs.createWriteStream(this.outputFile);
    doc.pipe(stream);

    // --- Cover Page ---
    doc.moveDown(6);
    doc.fontSize(28).font('Helvetica-Bold').fillColor('#1a1a2e')
      .text(this.suiteName, { align: 'center' });
    doc.moveDown(1);
    doc.fontSize(16).font('Helvetica').fillColor('#555')
      .text('Automated Test Execution Report', { align: 'center' });
    doc.moveDown(2);

    doc.fontSize(12).fillColor('#333');
    doc.text(`Date: ${this.startTime.toLocaleDateString('en-GB')}`, { align: 'center' });
    doc.text(`Time: ${this.startTime.toLocaleTimeString('en-GB')} - ${this.endTime.toLocaleTimeString('en-GB')}`, { align: 'center' });
    doc.text(`Duration: ${this._formatDuration(totalDuration)}`, { align: 'center' });
    doc.moveDown(3);

    // Summary box
    const boxX = 100;
    const boxY = doc.y;
    doc.roundedRect(boxX, boxY, 400, 120, 8).fillAndStroke('#f8f9fa', '#dee2e6');
    doc.fillColor('#333').fontSize(14).font('Helvetica-Bold');
    doc.text('Execution Summary', boxX + 20, boxY + 15, { width: 360, align: 'center' });
    doc.fontSize(12).font('Helvetica');
    doc.moveDown(0.5);
    const summaryY = boxY + 40;
    doc.fillColor('#28a745').text(`✅ Passed: ${passed}`, boxX + 30, summaryY + 10);
    doc.fillColor('#dc3545').text(`❌ Failed: ${failed}`, boxX + 30, summaryY + 28);
    doc.fillColor('#ffc107').text(`⏭ Skipped: ${skipped}`, boxX + 220, summaryY + 10);
    doc.fillColor('#6c757d').text(`⏱ Timed Out: ${timedOut}`, boxX + 220, summaryY + 28);
    doc.fillColor('#333').text(`📊 Total: ${this.results.length}`, boxX + 30, summaryY + 55);
    const passRate = this.results.length > 0 ? ((passed / this.results.length) * 100).toFixed(1) : 0;
    doc.text(`📈 Pass Rate: ${passRate}%`, boxX + 220, summaryY + 55);

    doc.moveDown(4);
    doc.fillColor('#888').fontSize(10)
      .text('Generated by CIFF Playwright Automation Framework', { align: 'center' });

    // --- Results by Project ---
    doc.addPage();
    doc.fontSize(20).font('Helvetica-Bold').fillColor('#1a1a2e')
      .text('Test Results by Module', { align: 'left' });
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#dee2e6').stroke();
    doc.moveDown(1);

    const byProject = {};
    for (const r of this.results) {
      const key = r.project || 'unknown';
      if (!byProject[key]) byProject[key] = [];
      byProject[key].push(r);
    }

    for (const [project, tests] of Object.entries(byProject)) {
      if (doc.y > 680) doc.addPage();

      const projPassed = tests.filter(t => t.status === 'passed').length;
      const projFailed = tests.filter(t => t.status === 'failed').length;

      doc.fontSize(14).font('Helvetica-Bold').fillColor('#2c3e50')
        .text(`📁 ${this._projectLabel(project)} (${projPassed}/${tests.length} passed)`);
      doc.moveDown(0.3);

      // Table header
      const tableX = 55;
      let tableY = doc.y;
      doc.roundedRect(tableX, tableY, 490, 20, 2).fill('#e9ecef');
      doc.fontSize(9).font('Helvetica-Bold').fillColor('#333');
      doc.text('Status', tableX + 5, tableY + 5, { width: 45 });
      doc.text('Test Case', tableX + 55, tableY + 5, { width: 310 });
      doc.text('Duration', tableX + 375, tableY + 5, { width: 60 });
      doc.text('Result', tableX + 440, tableY + 5, { width: 50 });
      tableY += 22;

      for (const t of tests) {
        if (tableY > 720) {
          doc.addPage();
          tableY = 60;
        }

        const statusIcon = t.status === 'passed' ? '✅' : t.status === 'failed' ? '❌' : t.status === 'skipped' ? '⏭' : '⏱';
        const statusColor = t.status === 'passed' ? '#d4edda' : t.status === 'failed' ? '#f8d7da' : '#fff3cd';

        doc.roundedRect(tableX, tableY, 490, 18, 1).fill(statusColor);
        doc.fontSize(8).font('Helvetica').fillColor('#333');
        doc.text(statusIcon, tableX + 5, tableY + 4, { width: 20 });
        doc.text(t.title.substring(0, 65), tableX + 55, tableY + 4, { width: 310 });
        doc.text(this._formatDuration(t.duration), tableX + 375, tableY + 4, { width: 60 });
        doc.font('Helvetica-Bold');
        doc.text(t.status.toUpperCase(), tableX + 440, tableY + 4, { width: 50 });
        doc.font('Helvetica');
        tableY += 20;
      }

      doc.moveDown(1);
      doc.y = tableY + 10;
    }

    // --- Failed Tests Detail ---
    const failedTests = this.results.filter(r => r.status === 'failed');
    if (failedTests.length > 0) {
      doc.addPage();
      doc.fontSize(20).font('Helvetica-Bold').fillColor('#dc3545')
        .text('❌ Failed Tests Detail', { align: 'left' });
      doc.moveDown(0.5);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#dee2e6').stroke();
      doc.moveDown(1);

      for (const t of failedTests) {
        if (doc.y > 600) doc.addPage();

        doc.fontSize(12).font('Helvetica-Bold').fillColor('#dc3545')
          .text(`❌ ${t.title}`);
        doc.fontSize(9).font('Helvetica').fillColor('#666')
          .text(`Project: ${t.project} | Duration: ${this._formatDuration(t.duration)} | Retry: ${t.retry}`);
        doc.moveDown(0.3);

        if (t.error) {
          doc.roundedRect(55, doc.y, 485, 50, 4).fill('#fff5f5');
          doc.fontSize(8).font('Courier').fillColor('#c0392b');
          const errorMsg = t.error.substring(0, 300);
          doc.text(errorMsg, 60, doc.y + 5, { width: 475 });
          doc.moveDown(1);
        }

        // Embed screenshots for failed tests
        for (const ss of t.screenshots) {
          if (ss.path && fs.existsSync(ss.path)) {
            if (doc.y > 400) doc.addPage();
            doc.fontSize(9).font('Helvetica').fillColor('#555')
              .text(`📸 Screenshot: ${ss.name}`);
            doc.moveDown(0.3);
            try {
              doc.image(ss.path, 55, doc.y, { width: 485 });
              doc.moveDown(1);
              doc.y += 280;
            } catch (e) {
              doc.text(`[Screenshot could not be embedded: ${e.message}]`);
            }
          }
        }
        doc.moveDown(1);
      }
    }

    // --- Passed Tests with Screenshots ---
    const passedWithScreenshots = this.results.filter(r => r.status === 'passed' && r.screenshots.length > 0);
    if (passedWithScreenshots.length > 0) {
      doc.addPage();
      doc.fontSize(20).font('Helvetica-Bold').fillColor('#28a745')
        .text('✅ Passed Tests — Screenshots', { align: 'left' });
      doc.moveDown(0.5);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#dee2e6').stroke();
      doc.moveDown(1);

      for (const t of passedWithScreenshots) {
        for (const ss of t.screenshots) {
          if (ss.path && fs.existsSync(ss.path)) {
            if (doc.y > 400) doc.addPage();
            doc.fontSize(10).font('Helvetica-Bold').fillColor('#28a745')
              .text(`✅ ${t.title}`);
            doc.fontSize(8).font('Helvetica').fillColor('#555')
              .text(`📸 ${ss.name}`);
            doc.moveDown(0.3);
            try {
              doc.image(ss.path, 55, doc.y, { width: 485 });
              doc.y += 280;
            } catch (e) {
              doc.text(`[Screenshot could not be embedded: ${e.message}]`);
            }
            doc.moveDown(1);
          }
        }
      }
    }

    // --- Footer with page numbers ---
    const pages = doc.bufferedPageRange();
    for (let i = pages.start; i < pages.start + pages.count; i++) {
      doc.switchToPage(i);
      doc.fontSize(8).fillColor('#aaa');
      doc.text(`Page ${i + 1} of ${pages.count}`, 50, 780, { align: 'center', width: 495 });
    }

    doc.end();

    await new Promise(resolve => stream.on('finish', resolve));
    console.log(`\n📄 PDF Report generated: ${this.outputFile}`);
    console.log(`   Tests: ${this.results.length} | Passed: ${passed} | Failed: ${failed} | Pass Rate: ${passRate}%\n`);
  }

  _formatDuration(ms) {
    if (ms < 1000) return `${ms}ms`;
    if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
    const mins = Math.floor(ms / 60000);
    const secs = ((ms % 60000) / 1000).toFixed(0);
    return `${mins}m ${secs}s`;
  }

  _projectLabel(project) {
    const labels = {
      'crm-setup': 'CRM Auth Setup',
      'fluxx-setup': 'Fluxx Auth Setup',
      'fabric-setup': 'Fabric Auth Setup',
      'crm-tests': 'CRM Tests',
      'fluxx-tests': 'Fluxx Tests',
      'fabric-tests': 'Fabric Tests',
      'integration': 'Integration & E2E',
    };
    return labels[project] || project;
  }
}

export default PdfReporter;
